name: schedule-workflow

on:
  schedule:
    - cron: "0 0 * * *"

jobs: 
  run-script:
    run-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "schedule workflow executed"
  
